language: go

go:
 - 1.1
 - 1.2
 - tip

install:
 - go get github.com/StefanKjartansson/stadfangaskra
 - go get github.com/gorilla/mux
 - go get github.com/gorilla/schema
 - go get github.com/llimllib/loglevel
 - go get github.com/golang/groupcache

script:
 - make STADFANGASKRA_DB=$GOPATH/src/github.com/StefanKjartansson/stadfangaskra/db.json
