language: go

go:
 - 1.1
 - 1.2
 - tip

install:
 - go get github.com/StefanKjartansson/isnet93
 - go get github.com/gorilla/mux
 - go get github.com/gorilla/schema
 - go get github.com/llimllib/loglevel
 - go get github.com/golang/groupcache
 - go get github.com/djimenez/iconv-go

script:
 - make
