language: go

go:
 - 1.1
 - tip

install:
 - go get github.com/StefanKjartansson/isnet93
 - go get github.com/gorilla/mux
 - go get github.com/gorilla/schema
 - go get github.com/llimllib/loglevel

script:
 - go test -v
